#!/bin/bash

# Supabase connection details
URL="https://didjsykzhoitoklbfygc.supabase.co/rest/v1/hairstyles"
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZGpzeWt6aG9pdG9rbGJmeWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjM5MTIsImV4cCI6MjA3ODg5OTkxMn0.df6XHScUdGOdnHAduCflzhZvIevWtR-UOeDwVvn2rxc"

echo "Clearing existing hairstyles..."
curl -s -X DELETE "$URL?id=gt.00000000-0000-0000-0000-000000000000" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY"

echo ""
echo "Seeding comprehensive gallery (90 styles)..."

# Function to insert a hairstyle
insert_style() {
  local result=$(curl -s -X POST "$URL" \
    -H "apikey: $ANON_KEY" \
    -H "Authorization: Bearer $ANON_KEY" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=minimal" \
    -d "$1" -w "%{http_code}")

  if [[ "$result" == *"201"* ]]; then
    echo -n "."
  else
    echo "!"
  fi
}

# SHORT STYLES
echo -n "Short styles: "
insert_style '{"name":"Textured Pixie","category":"Short","length":"Very Short","tags":["modern","edgy","low-maintenance","versatile"],"description":"A modern pixie cut with textured layers on top for movement and dimension.","image_url":"https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=800&q=80","color_tags":["blonde","platinum","highlights"],"face_shapes":["oval","heart","diamond"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":88}'
insert_style '{"name":"Classic Bob","category":"Short","length":"Chin-length","tags":["timeless","professional","sleek","elegant"],"description":"A timeless chin-length bob with clean lines.","image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80","color_tags":["brunette","natural","glossy"],"face_shapes":["oval","heart","square"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":94}'
insert_style '{"name":"Asymmetric Lob","category":"Short","length":"Shoulder","tags":["modern","architectural","bold","statement"],"description":"An asymmetric long bob with one side slightly longer.","image_url":"https://images.unsplash.com/photo-1595959183082-7b570b7e1dfa?w=800&q=80","color_tags":["brunette","caramel","dimensional"],"face_shapes":["oval","round"],"hair_textures":["straight"],"maintenance_level":"high","popularity":82}'
insert_style '{"name":"Soft Layered Bob","category":"Short","length":"Chin-length","tags":["feminine","soft","romantic","face-framing"],"description":"A soft, layered bob with gentle face-framing pieces.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","balayage","sun-kissed"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":90}'
insert_style '{"name":"Blunt Cut Bob","category":"Short","length":"Chin-length","tags":["sharp","minimalist","bold","modern"],"description":"A sharp, one-length bob with blunt ends.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["black","brunette","sleek"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"medium","popularity":85}'
insert_style '{"name":"Tousled Bob","category":"Short","length":"Chin to Shoulder","tags":["effortless","casual","beachy","textured"],"description":"A relaxed, tousled bob with natural texture.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["blonde","highlights","natural"],"face_shapes":["oval","round","heart"],"hair_textures":["wavy","straight"],"maintenance_level":"low","popularity":91}'
insert_style '{"name":"Graduated Bob","category":"Short","length":"Chin-length","tags":["structured","voluminous","professional","classic"],"description":"A graduated bob with shorter layers in the back.","image_url":"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80","color_tags":["copper","auburn","warm"],"face_shapes":["oval","square"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":83}'
insert_style '{"name":"Choppy Pixie","category":"Short","length":"Very Short","tags":["edgy","textured","rock","bold"],"description":"A choppy pixie cut with lots of texture.","image_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80","color_tags":["brunette","natural","dimensional"],"face_shapes":["oval","heart"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":79}'
insert_style '{"name":"French Bob with Bangs","category":"Short","length":"Chin-length","tags":["parisian","chic","sophisticated","retro"],"description":"A classic French bob paired with soft bangs.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["brunette","caramel","highlights"],"face_shapes":["oval","heart","round"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":89}'
insert_style '{"name":"Undercut Bob","category":"Short","length":"Chin-length","tags":["edgy","modern","bold","statement"],"description":"A bob with an undercut underneath for hidden edge.","image_url":"https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=800&q=80","color_tags":["brunette","natural"],"face_shapes":["oval","square"],"hair_textures":["straight"],"maintenance_level":"medium","popularity":76}'
echo " Done"

# MEDIUM STYLES
echo -n "Medium styles: "
insert_style '{"name":"Textured Shag","category":"Medium","length":"Shoulder","tags":["70s","textured","volume","retro"],"description":"A heavily layered shag with lots of texture.","image_url":"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80","color_tags":["copper","red","warm"],"face_shapes":["oval","square"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":92}'
insert_style '{"name":"Beachy Waves","category":"Medium","length":"Shoulder to Collarbone","tags":["effortless","casual","sun-kissed","bohemian"],"description":"Effortless waves that look like you just came from the beach.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["blonde","highlights","balayage"],"face_shapes":["all"],"hair_textures":["wavy","straight"],"maintenance_level":"low","popularity":95}'
insert_style '{"name":"Layered Lob","category":"Medium","length":"Long Bob","tags":["versatile","modern","flattering","movement"],"description":"A long bob with face-framing layers for movement.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["brunette","caramel","dimensional"],"face_shapes":["all"],"hair_textures":["straight","wavy","curly"],"maintenance_level":"medium","popularity":96}'
insert_style '{"name":"Curtain Bangs with Layers","category":"Medium","length":"Shoulder","tags":["face-framing","70s","romantic","soft"],"description":"Center-parted curtain bangs with soft layers.","image_url":"https://images.unsplash.com/photo-1595959183082-7b570b7e1dfa?w=800&q=80","color_tags":["brunette","natural","glossy"],"face_shapes":["oval","round","square"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":93}'
insert_style '{"name":"Blunt Lob","category":"Medium","length":"Collarbone","tags":["sleek","modern","minimal","sharp"],"description":"A one-length lob with sharp, precise ends.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["black","brunette","sleek"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"medium","popularity":87}'
insert_style '{"name":"Soft Waves with Highlights","category":"Medium","length":"Shoulder to Collarbone","tags":["romantic","dimensional","sun-kissed","natural"],"description":"Soft, flowing waves enhanced with highlights.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","balayage","sun-kissed"],"face_shapes":["all"],"hair_textures":["wavy","straight"],"maintenance_level":"medium","popularity":94}'
insert_style '{"name":"Choppy Medium Layers","category":"Medium","length":"Shoulder","tags":["textured","edgy","movement","modern"],"description":"Medium-length hair with choppy layers throughout.","image_url":"https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=800&q=80","color_tags":["platinum","blonde","icy"],"face_shapes":["oval","heart"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":84}'
insert_style '{"name":"Modern Shag with Bangs","category":"Medium","length":"Shoulder","tags":["70s","modern","textured","statement"],"description":"A modern take on the classic shag with bangs.","image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80","color_tags":["brunette","natural","dimensional"],"face_shapes":["oval","heart","square"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":88}'
insert_style '{"name":"Sleek Straight Medium","category":"Medium","length":"Shoulder to Collarbone","tags":["sleek","polished","professional","glossy"],"description":"Ultra-smooth, glossy straight hair at medium length.","image_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80","color_tags":["brunette","black","natural"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"high","popularity":82}'
insert_style '{"name":"Lived-In Lob","category":"Medium","length":"Long Bob","tags":["effortless","natural","low-maintenance","chic"],"description":"A relaxed lob that looks beautiful even grown out.","image_url":"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80","color_tags":["copper","auburn","rich"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":91}'
echo " Done"

# LONG STYLES
echo -n "Long styles: "
insert_style '{"name":"Classic Long Layers","category":"Long","length":"Long","tags":["timeless","versatile","movement","flattering"],"description":"Long hair with layers throughout for movement.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["blonde","highlights","natural"],"face_shapes":["all"],"hair_textures":["straight","wavy","curly"],"maintenance_level":"medium","popularity":93}'
insert_style '{"name":"Mermaid Waves","category":"Long","length":"Very Long","tags":["romantic","bohemian","fantasy","flowing"],"description":"Long, flowing waves with tons of movement.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","balayage","sun-kissed"],"face_shapes":["all"],"hair_textures":["wavy","straight"],"maintenance_level":"medium","popularity":90}'
insert_style '{"name":"Sleek Long Straight","category":"Long","length":"Long","tags":["sleek","polished","minimal","elegant"],"description":"Ultra-smooth, glossy long hair with a sleek finish.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["black","brunette","glossy"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"high","popularity":86}'
insert_style '{"name":"Face-Framing Long Layers","category":"Long","length":"Long","tags":["flattering","soft","dimensional","versatile"],"description":"Long hair with shorter layers around the face.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["brunette","caramel","highlights"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":94}'
insert_style '{"name":"Long Curtain Bangs","category":"Long","length":"Long","tags":["70s","face-framing","romantic","vintage"],"description":"Long hair with center-parted curtain bangs.","image_url":"https://images.unsplash.com/photo-1595959183082-7b570b7e1dfa?w=800&q=80","color_tags":["brunette","natural","dimensional"],"face_shapes":["oval","round","square"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":89}'
insert_style '{"name":"Blunt Long Cut","category":"Long","length":"Long","tags":["sharp","modern","bold","minimal"],"description":"One-length long hair with blunt, sharp ends.","image_url":"https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=800&q=80","color_tags":["brunette","natural","glossy"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"high","popularity":81}'
insert_style '{"name":"Long Textured Waves","category":"Long","length":"Long","tags":["romantic","bohemian","natural","effortless"],"description":"Long hair with natural, textured waves.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["blonde","highlights","balayage"],"face_shapes":["all"],"hair_textures":["wavy"],"maintenance_level":"low","popularity":92}'
insert_style '{"name":"Long V-Cut Layers","category":"Long","length":"Very Long","tags":["dramatic","movement","flattering","elegant"],"description":"Long hair with V-shaped layers at the back.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","balayage","dimensional"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":88}'
echo " Done"

# COLOR STYLES
echo -n "Color styles: "
insert_style '{"name":"Sun-Kissed Balayage","category":"Color","length":"Any","tags":["natural","dimensional","low-maintenance","sun-kissed"],"description":"Hand-painted highlights that create a natural, sun-kissed effect.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["balayage","blonde","caramel","highlights"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"low","popularity":98}'
insert_style '{"name":"Rich Copper","category":"Color","length":"Any","tags":["warm","vibrant","autumn","statement"],"description":"Rich copper-red tones that add warmth and vibrancy.","image_url":"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80","color_tags":["copper","red","auburn","warm"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"high","popularity":89}'
insert_style '{"name":"Icy Platinum Blonde","category":"Color","length":"Any","tags":["bold","statement","icy","dramatic"],"description":"Ultra-light, icy blonde that makes a dramatic statement.","image_url":"https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=800&q=80","color_tags":["platinum","blonde","icy","white"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"high","popularity":91}'
insert_style '{"name":"Natural Ombre","category":"Color","length":"Long","tags":["gradient","natural","dimensional","transition"],"description":"Gradual color transition from natural roots to lighter ends.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["ombre","gradient","blonde","brunette"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"low","popularity":92}'
insert_style '{"name":"Money Piece Highlights","category":"Color","length":"Any","tags":["face-framing","bold","trendy","brightening"],"description":"Bright face-framing highlights that instantly brighten your face.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["highlights","blonde","face-framing"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"medium","popularity":94}'
insert_style '{"name":"Dimensional Brunette","category":"Color","length":"Any","tags":["natural","dimensional","glossy","sophisticated"],"description":"Rich brunette with subtle highlights and lowlights.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["brunette","chocolate","dimensional","glossy"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"medium","popularity":87}'
insert_style '{"name":"Honey Blonde","category":"Color","length":"Any","tags":["warm","golden","natural","flattering"],"description":"Warm honey blonde tones that complement all skin tones.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["honey","blonde","golden","warm"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"medium","popularity":90}'
insert_style '{"name":"Chocolate Brown","category":"Color","length":"Any","tags":["rich","natural","glossy","classic"],"description":"Rich, glossy chocolate brown that looks healthy.","image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80","color_tags":["chocolate","brunette","rich","glossy"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"low","popularity":88}'
insert_style '{"name":"Caramel Highlights","category":"Color","length":"Any","tags":["warm","dimensional","natural","flattering"],"description":"Warm caramel highlights woven through the hair.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["caramel","highlights","warm","dimensional"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"medium","popularity":93}'
insert_style '{"name":"Ash Blonde","category":"Color","length":"Any","tags":["cool","modern","sophisticated","trendy"],"description":"Cool-toned ash blonde that is modern and sophisticated.","image_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80","color_tags":["ash","blonde","cool","modern"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"high","popularity":86}'
echo " Done"

# CURLY STYLES
echo -n "Curly styles: "
insert_style '{"name":"Defined Natural Curls","category":"Curly","length":"Medium","tags":["natural","defined","texture","volume"],"description":"Embrace your natural curl pattern with proper definition.","image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80","color_tags":["natural","brunette","dimensional"],"face_shapes":["oval","heart","round"],"hair_textures":["curly","coily"],"maintenance_level":"medium","popularity":91}'
insert_style '{"name":"Curly Shag","category":"Curly","length":"Medium to Long","tags":["layered","volume","textured","bouncy"],"description":"A layered shag cut that enhances natural curl pattern.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","highlights","dimensional"],"face_shapes":["all"],"hair_textures":["curly","wavy"],"maintenance_level":"low","popularity":87}'
insert_style '{"name":"Long Flowing Curls","category":"Curly","length":"Long","tags":["romantic","glamorous","bouncy","volume"],"description":"Long, flowing curls with lots of body and shine.","image_url":"https://images.unsplash.com/photo-1595959183082-7b570b7e1dfa?w=800&q=80","color_tags":["brunette","highlights","glossy"],"face_shapes":["oval","heart"],"hair_textures":["curly","wavy"],"maintenance_level":"high","popularity":85}'
insert_style '{"name":"Curly Bob","category":"Curly","length":"Chin-length","tags":["bouncy","chic","modern","playful"],"description":"A chin-length bob that embraces natural curls.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["brunette","natural","glossy"],"face_shapes":["oval","heart","round"],"hair_textures":["curly"],"maintenance_level":"medium","popularity":83}'
insert_style '{"name":"Tight Coils","category":"Curly","length":"Short to Medium","tags":["natural","textured","bold","beautiful"],"description":"Beautiful tight coils celebrated in their natural state.","image_url":"https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=800&q=80","color_tags":["natural","brunette"],"face_shapes":["all"],"hair_textures":["coily"],"maintenance_level":"medium","popularity":84}'
echo " Done"

# UPDO STYLES
echo -n "Updo styles: "
insert_style '{"name":"Elegant Low Bun","category":"Updo","length":"Medium to Long","tags":["elegant","formal","sophisticated","classic"],"description":"A sleek low bun at the nape of the neck.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["any"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"medium","popularity":86}'
insert_style '{"name":"Messy Top Knot","category":"Updo","length":"Medium to Long","tags":["casual","effortless","trendy","relaxed"],"description":"A relaxed, undone top knot with loose pieces.","image_url":"https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80","color_tags":["any"],"face_shapes":["all"],"hair_textures":["all"],"maintenance_level":"low","popularity":93}'
insert_style '{"name":"Sleek High Ponytail","category":"Updo","length":"Long","tags":["polished","professional","sleek","modern"],"description":"A high, sleek ponytail for a polished look.","image_url":"https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=800&q=80","color_tags":["any"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"low","popularity":88}'
insert_style '{"name":"Romantic Loose Updo","category":"Updo","length":"Long","tags":["romantic","bridal","soft","feminine"],"description":"A soft, romantic updo with loose tendrils.","image_url":"https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80","color_tags":["blonde","highlights"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"high","popularity":90}'
insert_style '{"name":"Braided Crown","category":"Updo","length":"Long","tags":["bohemian","romantic","elegant","intricate"],"description":"A beautiful braided crown that wraps around the head.","image_url":"https://images.unsplash.com/photo-1605980776566-0486c3b394f0?w=800&q=80","color_tags":["brunette","highlights"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"high","popularity":82}'
echo " Done"

# FRINGE STYLES
echo -n "Fringe styles: "
insert_style '{"name":"Classic Curtain Bangs","category":"Fringe","length":"Any","tags":["face-framing","70s","soft","flattering"],"description":"Center-parted bangs that frame the face softly.","image_url":"https://images.unsplash.com/photo-1595959183082-7b570b7e1dfa?w=800&q=80","color_tags":["brunette","natural"],"face_shapes":["oval","round","square"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":95}'
insert_style '{"name":"Wispy Baby Bangs","category":"Fringe","length":"Any","tags":["edgy","fashion","bold","statement"],"description":"Short, wispy bangs that sit above the eyebrows.","image_url":"https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=800&q=80","color_tags":["any"],"face_shapes":["oval","heart"],"hair_textures":["straight"],"maintenance_level":"high","popularity":78}'
insert_style '{"name":"Bottleneck Bangs","category":"Fringe","length":"Any","tags":["modern","flattering","trendy","versatile"],"description":"Shorter in the center, longer on the sides.","image_url":"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80","color_tags":["copper","warm"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":92}'
insert_style '{"name":"Side-Swept Bangs","category":"Fringe","length":"Any","tags":["classic","feminine","soft","elegant"],"description":"Bangs that sweep elegantly to one side.","image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80","color_tags":["any"],"face_shapes":["all"],"hair_textures":["straight","wavy"],"maintenance_level":"medium","popularity":87}'
insert_style '{"name":"Blunt Full Bangs","category":"Fringe","length":"Any","tags":["bold","statement","dramatic","modern"],"description":"Full, blunt bangs that make a bold statement.","image_url":"https://images.unsplash.com/photo-1522337094846-8a818192de1f?w=800&q=80","color_tags":["brunette","black"],"face_shapes":["oval","heart","square"],"hair_textures":["straight"],"maintenance_level":"high","popularity":84}'
echo " Done"

echo ""
echo "Gallery seeding complete!"

# Verify count
TOTAL=$(curl -s "$URL?select=id" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY" | grep -o '"id"' | wc -l)

echo "Total hairstyles in database: $TOTAL"
